.\"
.\" The original code by Ted Unangst is in public domain:
.\" <https://flak.tedunangst.com/post/sct-set-color-temperature>
.\" <https://flak.tedunangst.com/files/sct.c>
.\" Manual page written by zvezdochiot and others
.\" <https://github.com/faf0/sct/commits/master/xsct.1>.
.\" Typographically modified by me (rapidcow duh)
.\"
.TH XSCT 1 "2024-06-24" "xsct 2.3" "User Manual"
.SH NAME
xsct \- X11 set screen color temperature
.SH SYNOPSIS
.SY xsct 
.RB [ \-hvdt ]
.\" XXX: space? \[space] or \~ (GNU extension)?
.RB [ \-s \ \c
.IR N ]
.RB [ \-c \ \c
.IR N ]
.RI [ temperature ]
.RI [ brightness ]
.SH DESCRIPTION
.B xsct
sets the screen's color temperature.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display usage information and exit.
.TP
.BR \-v ", " \-\-verbose
Display debugging information.
.TP
.BR \-d ", " \-\-delta
Shift temperature and brightness relative to the
current temperature and brightness value.
.\" \continuing is necessary if we want them to
.\" stay on the same line of the tagged paragraph.
.TP
.BR \-s ", " \-\-screen\c
.RI " " N
.\" XXX: ... by screen you mean X display (:N), right
Zero-based index of screen to use.
.TP
.BR \-t ,\  \-\-toggle
Toggle between night and day temperature.
.TP
.BR \-c ,\  \-\-crtc\c
.RI " " N
Zero-based index of CRTC to use.
.TP
.RI [ temperature ]
Black body temperature.
.RS 9
.IP \[bu] 3
If the value is 0, xsct sets the color temperature to the default of 6500;
.IP \[bu] 3
If no arguments are passed, xsct estimates the current display temperature and brightness.
.RE
.\" This .P seems necessary to pad .RI/.RE
.P
.TP
.RI [ brightness ]
Linear brightness between 0.0 (inclusive) and 1.0 (inclusive).
The default value is 1.0 if no parameter is passed.
.SH AUTHOR
.B xsct is based on
.B sct
by Ted Unangst <tedu@openbsd.org>.
.SH SEE ALSO
.BR redshift (1),
.BR xtemp (1)
